security:
    encoders:
        MercurioBundle\Entity\User: bcrypt
    providers:
        database_users:
            entity: 
                class: MercurioBundle:User
    role_hierarchy:
        RULE_USER:        ROLE_UNFILLED_USER
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_API_USER, ROLE_ADMIN]
    access_control:
            - { path: ^/event, roles: ROLE_USER }
            - { path: ^/user, roles: ROLE_USER }
            - { path: ^/auth/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            guard:
                authenticators:
                    - app.form_login_authenticator
            logout:
                path: /auth/logout
                target: /
            form-login:
                login-path: /auth/login
                check-path: /auth/login
                csrf_token_generator: security.csrf.token_manager
            remember_me:
                secret:   '%secret%'
                path:     /